apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.platformApi.app.name }}
  namespace: {{ .Values.platformApi.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.platformApi.app.name }}
