hyperfleetAdapter1Chart:
  applicationName: hyperfleet-adapter1
  namespace: argocd
  targetNamespace: hyperfleet-system
  project: default
  source:
    repoURL: https://github.com/openshift-hyperfleet/hyperfleet-adapter
    path: charts
    targetRevision: main
  helmValues:
    image:
      registry: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet
      repository: hyperfleet-adapter
      tag: dev
      pullPolicy: Always
    replicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
secretProvider:
  name: hyperfleet-adapter1-secrets
