{{- if ne (toString .Values.pagerduty.enabled) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: pagerduty-integration-key
  namespace: monitoring
type: Opaque
stringData:
  integration_key: "disabled"
{{- end }}
