alert-bridge-chart:
  applicationName: alert-bridge
  namespace: argocd
  targetNamespace: monitoring
  project: default

  source:
    repoURL: https://github.com/iamkirkbater/rosa-alert-bridge.git
    targetRevision: main
    path: charts/rosa-alert-bridge

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  helmValues:
    image:
      repository: quay.io/iamkirkbater/rosa-alert-bridge
      tag: latest
      pullPolicy: Always

    serviceAccount:
      name: alert-sns-bridge

    config:
      logLevel: "info"
      snsTopicArnFromSecret:
        name: alert-bridge-sns-config
        key: sns-topic-arn

    serviceMonitor:
      enabled: true

    networkPolicy:
      enabled: true
      alertmanagerNamespace: "monitoring"

    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: alert-bridge-sns-config

    extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: /mnt/secrets-store
        readOnly: true

secretProviderClass:
  enabled: true
  name: alert-bridge-sns-config
  secretName: alert-bridge-sns-config
