defaults:
  revision: main
  bootstrap_pipeline_revision: main
  account_id: ssm:///infra/{{ environment }}/{{ aws_region }}/account_id
  management_cluster_account_id: ssm:///infra/{{ environment }}/{{ aws_region }}/{{
    cluster_prefix }}/account_id
  terraform_vars:
    app_code: infra
    service_phase: dev
    cost_center: '000'
    environment: '{{ environment }}'
    account_id: '{{ account_id }}'
    region: '{{ aws_region }}'
    alias: regional-{{ aws_region }}
  values:
    management-cluster:
      hypershift:
        oidcStorageS3Bucket:
          name: hypershift-mc-{{ aws_region }}
          region: '{{ aws_region }}'
        externalDns:
          domain: dev.{{ aws_region }}.rosa.example.com
    regional-cluster:
      maestro:
        mqttEndpoint: xxx.iot.{{ aws_region }}.amazonaws.com
      someOtherSetting: value
environments:
  cdoan-central:
    region_deployments:
      us-east-2:
        account_id: '754250776154'
        terraform_vars:
          enable_bastion: true
        management_clusters:
          mc01:
            account_id: '910485845704'
  integration:
    region_deployments:
      us-east-1:
        management_clusters:
          mc01: {}
      us-east-2:
        revision: 826fa76d08fc2ce87c863196e52d5a4fa9259a82
        management_clusters:
          mc01: {}
      eu-west-1:
        management_clusters:
          mc01: {}
  staging:
    terraform_vars:
      service_phase: staging
    region_deployments:
      us-east-1:
        management_clusters:
          mc01: {}
  brian:
    region_deployments:
      us-east-1:
        account_id: {}
        terraform_vars:
          enable_bastion: true
        management_clusters:
          mc01: {}
  psav-central:
    terraform_vars:
      enable_bastion: true
    region_deployments:
      us-east-1:
        management_clusters:
          mc01: {}
  ci:
    region_deployments:
      us-east-1:
        account_id: '633630779107'
        management_clusters:
          mc01:
            account_id: 018092638725
