apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-log-collector
  labels:
    {{- include "vector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-log-collector
  labels:
    {{- include "vector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-log-collector
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: {{ include "vector.namespace" . }}
