apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: {{ include "vector.namespace" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
  annotations:
    {{- include "vector.annotations" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sigv4-proxy-logs
  namespace: {{ include "vector.namespace" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
    app.kubernetes.io/component: logs-proxy
  annotations:
    {{- include "vector.annotations" . | nindent 4 }}
