management_cluster_defaults:
  enable_bastion: true

regional_cluster:
  enable_bastion: true
  enable_cloudtrail: false
  ou_path: "ssm:///infra/dev/e2e/ou-path"

observability:
  pagerduty:
    enabled: false
