regional_cluster:
  enable_bastion: true

management_cluster_defaults:
  enable_bastion: true

applications:
  regional-cluster:
    eksNodePool:
      enableFips: true
  management-cluster:
    eksNodePool:
      enableFips: true
