{{- if .Values.thanos.receive.enabled }}
apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosReceive
metadata:
  name: thanos-receive
  namespace: {{ include "thanos-operator.namespace" . }}
  labels:
    {{- include "thanos-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos-operator.annotations" . | nindent 4 }}
spec:
  ingesterSpec:
    defaultObjectStorageConfig:
      name: {{ .Values.objectStore.secretName }}
      key: objstore.yml
    hashrings:
      - name: default
        replicas: {{ .Values.thanos.receive.replicas }}
        tsdbConfig:
          retention: {{ .Values.thanos.receive.retention }}
        resourceRequirements:
          requests:
            cpu: {{ .Values.thanos.receive.resources.requests.cpu }}
            memory: {{ .Values.thanos.receive.resources.requests.memory }}
          limits:
            memory: {{ .Values.thanos.receive.resources.limits.memory }}
        storage:
          size: {{ .Values.thanos.receive.storage.size }}
          {{- if .Values.thanos.receive.storage.storageClass }}
          storageClass: {{ .Values.thanos.receive.storage.storageClass }}
          {{- end }}
  routerSpec:
    replicas: {{ .Values.thanos.receive.router.replicas | default 1 }}
    replicationFactor: {{ .Values.thanos.receive.replicationFactor }}
    resourceRequirements:
      requests:
        cpu: {{ .Values.thanos.receive.router.resources.requests.cpu }}
        memory: {{ .Values.thanos.receive.router.resources.requests.memory }}
      limits:
        memory: {{ .Values.thanos.receive.router.resources.limits.memory }}
    additionalArgs:
      - "--receive.default-tenant-id=default-tenant"
    externalLabels:
      receive: "true"
      region: {{ .Values.global.aws_region | quote }}
{{- end }}
