hyperfleetSentinelChart:
  applicationName: hyperfleet-sentinel
  namespace: argocd
  targetNamespace: hyperfleet-system
  project: default
  source:
    repoURL: https://github.com/cdoan1/hyperfleet-sentinel.git
    path: charts
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
  values:
    image:
      registry: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet
      repository: hyperfleet-sentinel
      tag: dev
      pullPolicy: Always
    replicaCount: 1
    broker:
      type: rabbitmq
      topic: clusters
      rabbitmq:
        url: amqps://placeholder:placeholder@localhost:5671/
        exchangeType: topic
        exchange: hyperfleet
        routingKey: clusters
    env:
    - name: BROKER_RABBITMQ_URL
      valueFrom:
        secretKeyRef:
          name: hyperfleet-sentinel-broker-credentials
          key: BROKER_RABBITMQ_URL
    subscriber:
      parallelism: 1
    config:
      log:
        level: debug
        format: json
        output: stdout
      resourceType: clusters
      resourceSelector: []
      pollInterval: 5s
      clients:
        hyperfleetApi:
          baseUrl: http://hyperfleet-api:8000
          version: v1
          timeout: 5s
      messageData:
        id: resource.id
        kind: resource.kind
        href: resource.href
        generation: resource.generation
    existingSecret: hyperfleet-sentinel-broker-credentials
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: ''
      name: sentinel-sa
    extraVolumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: hyperfleet-sentinel-secrets
    extraVolumeMounts:
    - name: secrets-store-inline
      mountPath: /mnt/secrets-store
      readOnly: true
secretProvider:
  enabled: true
  name: hyperfleet-sentinel-secrets
  aws:
    region: us-east-1
    secrets:
    - objectName: hyperfleet-sentinel/broker-credentials
      objectType: secretsmanager
      jmesPath:
      - path: url
        objectAlias: url
  secretObjects:
  - secretName: hyperfleet-sentinel-broker-credentials
    type: Opaque
    data:
    - objectName: url
      key: url
