version: 0.2

env:
  shell: bash

phases:
  build:
    on-failure: RETRY-1
    commands:
      - ./scripts/buildspec/provision-infra-rc.sh

  post_build:
    commands:
      - echo "Infrastructure deployment complete."
artifacts:
  files:
    - '**/*'
    - terraform/config/regional-cluster/outputs.json
  exclude-paths:
    - '**/.terraform/**'
    - '**/.terraform.lock.hcl'
    - '**/node_modules/**'
