apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: fips
spec:
  role: "{{ .Values.global.cluster_name }}-auto-node-role"
  subnetSelectorTerms:
    - tags:
        "kubernetes.io/cluster/{{ .Values.global.cluster_name }}": owned
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "{{ .Values.global.cluster_name }}"
  amiFamily: Custom
  amiSelectorTerms:
    {{- range .Values.eksNodeClass.amiIds }}
    - id: {{ . }}
    {{- end }}
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
    httpPutResponseHopLimit: 2
  userData: |
    #!/bin/bash
    cat > /etc/eks/bootstrap-config.env << 'EOF'
    CLUSTER_NAME={{ .Values.global.cluster_name }}
    APISERVER_ENDPOINT={{ .Values.global.apiserver_endpoint }}
    B64_CLUSTER_CA={{ .Values.global.cluster_ca }}
    CLUSTER_DNS=172.20.0.10
    EOF
