global:
  cluster_name: <cluster-name>
  region: us-east-1

eksNodeClass:
  amiIds:
    - ami-07422e7eda1def74c # RHEL 9 FIPS K8s 1.34 us-east-1
    # Add 1.35 and 1.36 AMI IDs here once built

eksNodePool:
  instanceFamilies:
    - m8i
    - m7i
  capacityType: on-demand
  arch: amd64
  limits:
    cpu: "64"
    memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
