apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.hyperfleetApiChart.name }}
  namespace: {{ .Values.hyperfleetApiChart.namespace }}
  {{- if .Values.hyperfleetApiChart.annotations }}
  annotations:
    {{- toYaml .Values.hyperfleetApiChart.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "hyperfleet-api-chart.labels" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: {{ .Values.hyperfleetApiChart.source.repoURL }}
    targetRevision: {{ .Values.hyperfleetApiChart.source.targetRevision }}
    path: {{ .Values.hyperfleetApiChart.source.path }}
    {{- if .Values.hyperfleetApiChart.values }}
    helm:
      values: |
        {{- toYaml .Values.hyperfleetApiChart.values | nindent 8 }}
      valuesObject:
        values:
          database:
            external:
              aws:
                region: {{ .Values.global.aws_region }}
                secretName: "{{ .Values.global.cluster_name }}-hyperfleet-db-credentials"
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.hyperfleetApiChart.targetNamespace }}
  syncPolicy:
    {{- toYaml .Values.hyperfleetApiChart.syncPolicy | nindent 4 }}
