region_deployments:
  us-east-1:
    account_id: {}
    terraform_vars:
      enable_bastion: true
      container_image: quay.io/redhat-services-prod/openshift/ocm-container:latest
    management_clusters:
      mc01: {}
