apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.hyperfleetSentinel1Chart.name }}
  namespace: {{ .Values.hyperfleetSentinel1Chart.namespace }}
  {{- if .Values.hyperfleetSentinel1Chart.annotations }}
  annotations:
    {{- toYaml .Values.hyperfleetSentinel1Chart.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "hyperfleet-sentinel1-chart.labels" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: {{ .Values.hyperfleetSentinel1Chart.source.repoURL }}
    targetRevision: {{ .Values.hyperfleetSentinel1Chart.source.targetRevision }}
    path: {{ .Values.hyperfleetSentinel1Chart.source.path }}
    {{- if .Values.hyperfleetSentinel1Chart.values }}
    helm:
      values: |
        {{- toYaml .Values.hyperfleetSentinel1Chart.values | nindent 8 }}
    valuesObject:
      broker:
        external:
          aws:
            region: {{ .Values.global.aws_region }}
            secretName: "{{ .Values.global.cluster_name }}-hyperfleet-mq-credentials"
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.hyperfleetSentinel1Chart.targetNamespace }}
  syncPolicy:
    {{- toYaml .Values.hyperfleetSentinel1Chart.syncPolicy | nindent 4 }}
