apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: {{ include "vector.namespace" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
  annotations:
    {{- include "vector.annotations" . | nindent 4 }}
