apiVersion: v1
kind: Service
metadata:
  name: vector-metrics
  namespace: {{ include "vector.namespace" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
  annotations:
    {{- include "vector.annotations" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "vector.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
