hyperfleet-api-chart:
  applicationName: hyperfleet-api
  namespace: argocd
  targetNamespace: hyperfleet-system
  project: default
  source:
    repoURL: https://github.com/openshift-hyperfleet/hyperfleet-api.git
    targetRevision: main
    path: charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  helmValues:
    image:
      registry: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet
      repository: hyperfleet-api
      tag: dev
      pullPolicy: Always
    replicaCount: 2
    config:
      database:
        ssl:
          mode: require
      adapters:
        required:
          cluster:
          - adapter1
          nodepool:
          - adapter3
    database:
      postgresql:
        enabled: false
      external:
        enabled: true
        secretName: hyperfleet-api-db-credentials
    serviceAccount:
      name: hyperfleet-api-sa
    extraVolumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: hyperfleet-api-aws-credentials
    extraVolumeMounts:
    - name: secrets-store-inline
      mountPath: /mnt/secrets-store
      readOnly: true
secretProviderClass:
  enabled: true
  name: hyperfleet-api-aws-credentials
