POLL_INTERVAL = 30
PIPELINE_TRIGGER_TIMEOUT = 600  # 10 minutes
PIPELINE_COMPLETION_TIMEOUT = 7200  # 120 minutes; EKS cluster creation can take 26+ min on slow AWS days
PIPELINE_DISCOVERY_TIMEOUT = 600  # 10 minutes
TARGET_ENVIRONMENT = "ephemeral"
