apiVersion: v2
name: loki-operator
description: A Helm chart with loki-operator as subchart
type: application
version: 0.1.0

dependencies:
  - name: loki-operator
    version: 0.10.0
    repository: oci://quay.io/slopezz/loki-operator-chart
